version: '3.1'

services:
  kali:
    container_name: kaliCP
    build:
      dockerfile: Dockerfile
      context: .
    network_mode: "host"
    volumes:
      - kaliUser:$HOME
      - kaliRoot:/root
    entrypoint: /bin/bash
    stdin_open: true # docker run -i
    tty: true        # docker run -t

volumes:
  kaliUser:
  kaliRoot:
